default: &default
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: toor
  host: 127.0.0.1

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  database: production